### ISSUE TITLE
Random Spawn

### ISSUE THREAD

**Issue by chiendom123** [brysonsteck/resurrection#5] opened 2022-01-23 13:23 UTC
it's a very cool plugin for pvp servers, but minecraft's random spawn feature is gone when i use this plugin. It's a very important feature in pvp server, please fix it

**Comment by brysonsteck** [comment] 2022-01-23 16:31
Hey there!!

Could you please fill out a bug report in a comment using [this template?](https://github.com/brysonsteck/resurrection/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) This will help me understand more what the issue is and where you're coming from. 

Thanks!

**Comment by brysonsteck** [comment] 2022-01-30 08:55
Hey! Just commenting to bump the issue. I will close it in 24 hours due to inactivity, but I will reopen if you respond with the bug report :)

**Comment by chiendom123** [comment] 2022-01-30 19:00
---
name: Random spawn
about: Report to improve plugin
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
In vanilla, when you die you will be spawned in a random location depending on the setting /gamerule SpawnRadius <Values>. But when installing the plugin, you will only respawn at a certain time.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a point far away from the spawn point
2. Die in many ways like /kill or to die from blood loss
3. Click "Respawn"
4. Return to the single respawn point

**Expected behavior**
It must respawn at another random point a configurable distance from the origin.

**Screenshots**
none

**Server Info (please complete the following information if you are the server admin):**
 - OS: Linux 
 - OS Version:  5.4.0-94-generic
 - Minecraft Server: Purpur
 - Minecraft Version: 1.18.1
 - Plugin Version: 1.3

**Other Plugins Running**
PublicCrafters
AdvancedLogin
AntiNetherRoof
bloodmoon
claimchunk
EliteMobs
GSit
LethalsEndermenTP
LibsDisguises
LuckPerms
NoCheatPlus
ProtocolLib
SimpleTpa
SkinsRestorer
TAB
Vault
worldedit-bukkit
worldguard-bukkit

**Additional context**
none

**Comment by brysonsteck** [comment] 2022-01-31 21:25
Perfect! Now I can see where you are coming from.

This is an intended feature of Resurrection to lock the player at spawn, but it seems that you can change where they spawn by increasing `SpawnRadius`. I'm sure this is something I can fix, but there isn't an estimated time on when it will be released yet. I will keep you updated though, thank you for the issue! Let me know if there is anything else I can do for you.

**Comment by brysonsteck** [comment] 2022-02-17 07:03
Hey there! Just wanted to give you an update since I finally got some time to work on it.

I found the source of the issue and it was relatively easy to fix. I just need to make sure that it is implemented in the rest of the player listener before committing a release. Expect a new version in the next two days!

**Comment by brysonsteck** [comment] 2022-02-27 20:27
I'll be releasing the Jar files later today!

**Closed** 2022-02-27 20:26 UTC
Labels: enhancement
